# === BUILDER/TEST STAGE ===
FROM node:23-alpine AS builder

WORKDIR /app

# Kopierar package.json och package-lock.json för att installera beroenden
# Detta steg utnyttjar Docker's cache. Om dessa filer inte ändras,
COPY package*.json ./

# Installerar alla beroenden, inklusive utvecklingsberoenden

RUN npm install

# Kopierar över all källkod
COPY . .

RUN npm test

# === RUNTIME STAGE ===

FROM node:23-alpine

WORKDIR /app

# Kopierar endast produktionsberoendena från 'builder'-steget
COPY --from=builder /app/node_modules ./node_modules

# Kopierar endast de filer som behövs för att köra applikationen

COPY --from=builder /app/*.js ./
COPY --from=builder /app/public ./

EXPOSE 3000

CMD ["npm", "run", "dev"]