name: Docker CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image backend
        run: docker build -t theunseenbug/test:latest .
        working-directory: ./backend

      - name: Build Docker image frontend
        run: docker build -t theunseenbug/frontend:latest .
        working-directory: ./frontend

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies frontend
        run: npm install
        working-directory: ./frontend

      - name: Run tests
        run: npm test
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend
